export const GET_ALBUMS_REQUEST = 'GET_ALBUMS_REQUEST';
export const GET_ALBUMS_SUCCESS = 'GET_ALBUMS_SUCCESS';
export const GET_ALBUMS_ERROR = 'GET_ALBUMS_ERROR';
export const NO_RESULTS = 'NO_RESULTS';

export const CHANGE_PAGE_NUMBER = 'CHANGE_PAGE_NUMBER';
